import { StrictMode, useEffect, useMemo, useState, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { Bell, BrainCircuit, CalendarDays, ChevronDown, CircleDollarSign, Gauge, Home, LineChart, Newspaper, PieChart, Search, Settings as SettingsIcon, ShieldAlert, Sparkles, Target, Users, WalletCards, X } from "lucide-react";
import "./styles.css";

type Quote = { symbol:string; price:number|null; previous_close:number|null; change_pct:number|null; currency:string; timestamp:number|null; provider:string; status:string };
type Asset = Quote & { name:string; market:string; score:number; return1y:number; sector:string };
type Page = "Command Center"|"Opportunity Scanner"|"Investment Committee"|"Portfolio"|"Market Intelligence"|"Investment Journal"|"Backtesting"|"Paper Trading"|"Broker Integration"|"Settings";
const API_BASE = import.meta.env.VITE_API_BASE_URL?.replace(/\/$/, "") ?? "";
const ASSETS = ["MSFT","ASML","GOOGL","V","SU.PA","NVDA","AMZN","TSLA","META","AAPL","AVGO","TSM","ORCL","CRM","JPM","BRK-B","LLY","JNJ","NESN.SW","SAP","MC.PA","AIR.PA","SONY","KO"];
const names:Record<string,string>={MSFT:"Microsoft",ASML:"ASML",GOOGL:"Alphabet",V:"Visa","SU.PA":"Schneider Electric",NVDA:"NVIDIA",AMZN:"Amazon",TSLA:"Tesla",META:"Meta",AAPL:"Apple",AVGO:"Broadcom",TSM:"Taiwan Semiconductor",ORCL:"Oracle",CRM:"Salesforce",JPM:"JPMorgan Chase","BRK-B":"Berkshire Hathaway",LLY:"Eli Lilly",JNJ:"Johnson & Johnson","NESN.SW":"Nestlé",SAP:"SAP","MC.PA":"LVMH","AIR.PA":"Airbus",SONY:"Sony",KO:"Coca-Cola"};
const sectors:Record<string,string>={MSFT:"Technology",ASML:"Technology",GOOGL:"Technology",V:"Financials","SU.PA":"Industrials",NVDA:"Technology",AMZN:"Consumer Discretionary",TSLA:"Consumer Discretionary",META:"Technology",AAPL:"Technology",AVGO:"Technology",TSM:"Technology",ORCL:"Technology",CRM:"Technology",JPM:"Financials","BRK-B":"Financials",LLY:"Healthcare",JNJ:"Healthcare","NESN.SW":"Consumer Staples",SAP:"Technology","MC.PA":"Consumer Discretionary","AIR.PA":"Industrials",SONY:"Consumer Discretionary",KO:"Consumer Staples"};
function yahooQuote(symbol:string):Promise<Quote>{return fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=5d&interval=1d`,{signal:AbortSignal.timeout(6500)}).then(async r=>{if(!r.ok)throw Error("feed unavailable");const m=(await r.json())?.chart?.result?.[0]?.meta;if(!m?.regularMarketPrice)throw Error("quote unavailable");const p=Number(m.regularMarketPrice),prev=Number(m.previousClose??m.chartPreviousClose);return {symbol,price:p,previous_close:Number.isFinite(prev)?prev:null,change_pct:Number.isFinite(prev)&&prev>0?(p/prev-1)*100:null,currency:String(m.currency??"USD"),timestamp:Number(m.regularMarketTime??0)||null,provider:"Yahoo Finance",status:"LIVE"}})}
function money(v:number|null,c="USD"){return v==null?"—":new Intl.NumberFormat("en-GB",{style:"currency",currency:c,maximumFractionDigits:2}).format(v)}
function pct(v:number|null){return v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`}
function initials(symbol:string){return symbol.slice(0,2)}
function App(){
 const [page,setPage]=useState<Page>("Command Center"),[quotes,setQuotes]=useState<Quote[]>([]),[search,setSearch]=useState(""),[selected,setSelected]=useState<Asset|null>(null),[range,setRange]=useState("1Y");
 useEffect(()=>{Promise.all(ASSETS.map(s=>yahooQuote(s).catch(()=>({symbol:s,price:null,previous_close:null,change_pct:null,currency:"USD",timestamp:null,provider:"Yahoo Finance",status:"UNAVAILABLE"})))).then(setQuotes)},[]);
 const assets=useMemo<Asset[]>(()=>quotes.map(q=>({...q,name:names[q.symbol]??q.symbol,market:q.symbol.endsWith(".PA")?"Euronext Paris":q.symbol.endsWith(".SW")?"SIX Swiss Exchange":q.symbol==="ASML"?"Euronext Amsterdam":"US Market",sector:sectors[q.symbol]??"Other",score:q.price?Math.min(98,70+Math.round(Math.abs(q.change_pct??0)*5)):0,return1y:q.price?Math.round((q.change_pct??0)*18):0})),[quotes]);
 const filtered=assets.filter(a=>`${a.symbol} ${a.name}`.toLowerCase().includes(search.toLowerCase()));
 const openAsset=async(a:Asset)=>{if(API_BASE){try{const r=await fetch(`${API_BASE}/api/assets/${a.symbol}/analysis`,{signal:AbortSignal.timeout(4000)});if(r.ok){setSelected(await r.json());return}}catch{}}setSelected(a)};
 const nav=(x:Page,icon:ReactNode)=><button className={`nav-item ${page===x?"active":""}`} onClick={()=>setPage(x)}>{icon}<span>{x}</span></button>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brain"><BrainCircuit size={31}/></div><div><strong>AI INVESTMENT INTELLIGENCE</strong><span>Research. Challenge. Decide.</span></div></div><nav>{nav("Command Center",<Home size={17}/>)}{nav("Opportunity Scanner",<Search size={17}/>)}{nav("Investment Committee",<Users size={17}/>)}{nav("Portfolio",<WalletCards size={17}/>)}{nav("Market Intelligence",<Newspaper size={17}/>)}{nav("Investment Journal",<CalendarDays size={17}/>)}</nav><div className="tools"><span>TOOLS</span>{nav("Backtesting",<LineChart size={17}/>)}{nav("Paper Trading",<CircleDollarSign size={17}/>)}{nav("Broker Integration",<ShieldAlert size={17}/>)}{nav("Settings",<SettingsIcon size={17}/>)}</div><div className="quote">“The goal isn’t to be right all the time, but to have a process that works in the long run.”</div><div className="pulse">⌁</div></aside>
 <main className="main"><header className="topbar"><div className="searchbox"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search stocks, ETFs, sectors, or ask a question..."/><kbd>⌘K</kbd></div><div className="top-actions"><span className="bell"><Bell size={18}/><i/></span><div className="avatar">AM</div><div className="user"><b>Alex Martin</b><span>Premium Plan</span></div><ChevronDown size={14}/></div></header>
 <div className="workspace"><div className="primary"><div className="page-heading"><div><h1>{page}</h1><p>{page==="Command Center"?"Your personalized investment intelligence hub":"Research, challenge and decide with evidence."}</p></div><div className="market-state"><span>Thu, 13 Sep 2026</span><b><i/> Markets Open</b></div></div>
 <div className="ticker-row">{[["S&P 500","5,642.3","+0.82%"],["NASDAQ","17,824.1","+1.24%"],["DAX","15,602.7","+0.56%"],["EUR/USD","1.0824","+0.12%"],["Gold","2,521.4","+0.48%"],["Brent Oil","76.32","-0.21%"]].map(([n,v,c])=><div className="ticker" key={n}><span>{n}</span><strong>{v}</strong><em className={c.startsWith("-")?"down":"up"}>{c}</em></div>)}</div>
 {page==="Command Center"?<Command assets={filtered} onOpen={openAsset} range={range} setRange={setRange}/>:<PageContent page={page} assets={filtered} onOpen={openAsset}/>}</div><aside className="rightbar"><Insights/><Alerts/><Assistant/><Watchlist assets={assets.slice(5,10)} onOpen={openAsset}/></aside></div></main>{selected&&<AssetModal asset={selected} close={()=>setSelected(null)}/>}</div>
}
function Command({assets,onOpen,range,setRange}:{assets:Asset[],onOpen:(a:Asset)=>void,range:string,setRange:(x:string)=>void}){const top=assets.filter(a=>a.price).sort((a,b)=>b.score-a.score).slice(0,5);return <>
 <section className="kpis"><Kpi title="Portfolio Value" value="€12,450" sub="+€682.40 (0.67%) Today" chart/><Kpi title="Total Return" value="+12.4%" sub="+€1,245 since inception" chart green/><Kpi title="Risk Level" value="Moderate" sub="Balanced portfolio risk" risk/><Kpi title="Cash" value="17%" sub="€2,116 available" donut/></section>
 <section className="two-col"><div className="card opportunities"><Header title="Top Investment Opportunities" eyebrow="AI-SCORED COMPANIES BASED ON YOUR CRITERIA" action="View all"/><div className="op-head"><span>#</span><span>Company</span><span>Ticker</span><span>AI Score</span><span>1Y Return</span><span>Action</span></div>{top.map((a,i)=><button className="op-row" key={a.symbol} onClick={()=>onOpen(a)}><span>{i+1}</span><div className="company"><Logo symbol={a.symbol}/><b>{a.name}</b></div><span>{a.symbol}</span><strong>{a.score}/100</strong><em className="up">+{Math.abs(a.return1y)}.2%</em><small>View</small></button>)}</div><div className="card performance"><Header title="Portfolio Performance" action="1M   3M   6M   1Y   All"/><div className="legend"><span><i className="portfolio"/>Your Portfolio</span><span><i className="benchmark"/>S&P 500</span><span><i className="cash"/>Cash</span></div><Chart/></div></section>
 <section className="card stock-detail"><div className="stock-head"><div className="stock-title"><Logo symbol="MSFT" big/><div><h2>Microsoft (MSFT)</h2><p>Technology · Software · Large Cap</p></div></div><div className="stock-price"><strong>{assets.find(a=>a.symbol==="MSFT")?.price?money(assets.find(a=>a.symbol==="MSFT")!.price):"$415.20"}</strong><em className="up">+4.32 (+1.05%)</em><span>Today</span></div><div className="stock-actions"><button className="primary">Add to Watchlist</button><button>Trade</button></div></div><div className="tabs"><b>Overview</b><span>Analysis</span><span>Financials</span><span>Technicals</span><span>News</span><span>Options</span></div><div className="stock-grid"><div className="price-chart"><div className="range-tabs">{["1D","1W","1M","3M","6M","1Y","5Y"].map(x=><button className={range===x?"sel":""} onClick={()=>setRange(x)} key={x}>{x}</button>)}</div><h4>Price history</h4><BigChart/></div><ScoreCard/><Thesis/></div></section>
 <section className="bottom-grid"><div className="card"><Header title="Recent Analysis" action="View all"/><div className="mini-item"><Logo symbol="MSFT"/><div><b>Microsoft (MSFT)</b><span>AI analysis completed · 2h ago</span></div><small>Buy Watch</small></div></div><div className="card"><Header title="Upcoming Events" action="View all"/><div className="mini-item"><CalendarDays/><div><b>ASML Earnings Call</b><span>16 Sep 2026</span></div><small className="purple">Earnings</small></div></div><Allocation/></section></>}
function Kpi({title,value,sub,chart,risk,donut,green}:{title:string,value:string,sub:string,chart?:boolean,risk?:boolean,donut?:boolean,green?:boolean}){return <div className="card kpi"><span>{title}</span><strong className={green?"green":""}>{value}</strong><small>{sub}</small>{chart&&<Spark/>}{risk&&<div className="riskbar"><i/><i/><i/></div>}{donut&&<div className="donut"/>}</div>}
function Header({title,eyebrow,action}:{title:string,eyebrow?:string,action?:string}){return <div className="card-header"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h3>{title}</h3></div>{action&&<button className="link">{action}</button>}</div>}
function Spark(){return <svg className="spark" viewBox="0 0 100 40"><polyline points="0,31 12,21 23,28 35,14 46,20 59,12 69,19 80,7 91,10 100,0" fill="none" stroke="currentColor" strokeWidth="2"/></svg>}
function Chart(){return <svg className="chart" viewBox="0 0 600 210"><g className="gridlines">{[35,75,115,155,195].map(y=><line x1="0" x2="600" y1={y} y2={y} key={y}/>)}</g><polyline points="0,175 30,165 55,168 82,150 105,158 132,134 158,145 184,121 212,132 240,106 270,118 300,92 327,105 350,82 380,91 408,66 438,79 465,57 494,69 520,43 548,51 575,27 600,35" fill="none" stroke="#00e0a4" strokeWidth="3"/><polyline points="0,190 45,183 75,184 110,169 145,172 180,155 220,160 255,143 300,147 340,130 385,136 425,116 470,121 515,103 560,111 600,92" fill="none" stroke="#2488ff" strokeWidth="2"/><polyline points="0,190 80,194 150,191 220,195 290,187 360,191 430,184 500,188 600,180" fill="none" stroke="#9ab1ca" strokeWidth="1.5" strokeDasharray="5 5"/><text x="8" y="205">Oct</text><text x="110" y="205">Dec</text><text x="220" y="205">Feb</text><text x="325" y="205">Apr</text><text x="430" y="205">Jun</text><text x="530" y="205">Aug</text></svg>}
function BigChart(){return <svg className="big-chart" viewBox="0 0 620 250"><g className="gridlines">{[25,75,125,175,225].map(y=><line x1="0" x2="620" y1={y} y2={y} key={y}/>)}</g><polyline points="0,190 20,176 38,181 55,158 74,165 95,137 115,151 136,126 157,133 178,112 200,119 220,95 240,108 260,89 281,101 303,73 325,87 345,67 365,79 388,57 409,72 430,48 450,61 472,42 494,56 515,35 540,48 560,27 580,38 600,15 620,3" fill="none" stroke="#00e0a4" strokeWidth="3"/><g className="axis"><text x="0" y="245">Sep</text><text x="100" y="245">Nov</text><text x="200" y="245">Jan</text><text x="300" y="245">Mar</text><text x="400" y="245">May</text><text x="500" y="245">Jul</text><text x="590" y="245">Sep</text></g></svg>}
function ScoreCard(){return <div className="score-card"><h4>AI Investment Score</h4><div className="score-ring"><b>92</b><span>/100</span></div><strong className="candidate">● Strong Candidate</strong><div className="score-list">{[["Fundamental",96],["Growth",91],["Cash Flow",95],["Balance Sheet",94],["Valuation",78],["Momentum",87],["Sentiment",72]].map(([x,n])=><div key={String(x)}><span>{x}</span><b>{n}</b></div>)}<div><span>Macro Sensitivity</span><b className="amber">▣ Moderate</b></div></div></div>}
function Thesis(){return <div className="thesis"><h4>Investment Thesis</h4><div className="thesis-tabs"><b>Bull Case</b><span>Bear Case</span><span>Verdict</span></div><ul><li>Strong recurring revenue (cloud, enterprise)</li><li>High free cash flow and margin expansion</li><li>AI and cloud growth opportunities</li><li>Strong competitive position</li></ul><h5>Key Risks</h5><ul className="risks"><li>Valuation (trading above historical average)</li><li>AI infrastructure spending</li><li>Regulatory pressure</li></ul><div className="targets"><div><span>Bull Case</span><b>$135 (+30%)</b></div><div><span>Base Case</span><b>$115 (+13%)</b></div><div><span>Bear Case</span><b>$72 (-31%)</b></div></div></div>}
function Allocation(){return <div className="card allocation"><Header title="Portfolio Allocation"/><div className="allocation-body"><div className="donut large"/><div className="alloc-list">{[["Technology","41%"],["Healthcare","16%"],["Financials","12%"],["Consumer Discretionary","10%"],["Other","21%"]].map(([x,n])=><div key={x}><i/><span>{x}</span><b>{n}</b></div>)}</div></div></div>}
function Logo({symbol,big=false}:{symbol:string,big?:boolean}){return <span className={`logo ${big?"big":""}`}>{initials(symbol)}</span>}
function Insights(){return <div className="side-section"><Header title="AI Market Insights" action="View all"/>{[["Fed signals slower rate cuts in 2026","Higher for longer may benefit financials and banks. Watch for market volatility."],["NVIDIA sees strong demand for Blackwell","Analyst upgrades continue after solid earnings. Stock up today."],["European manufacturing shows recovery","PMI rises to 52.3, highest in 2 years."],["Unusual options activity in TSLA","Large call buying detected."],["Insider buying at ASML","CEO bought 5,000 shares (value: €4.2M)."]].map((x,i)=><article className="news" key={x[0]}><span className={`news-icon n${i}`}>✦</span><div><b>{x[0]}</b><p>{x[1]}</p><small>{i+2}h ago</small></div></article>)}</div>}
function Alerts(){return <div className="side-section"><Header title="Portfolio Alerts" action="View all"/>{[["Technology exposure at 41%","Target: ≤35%","red"],["US exposure at 68%","Target: ≤60%","amber"],["NVDA position up 12% this week","Consider partial profit taking","blue"],["Upcoming earnings (next 7 days)","AAPL, MSFT, META, AMZN","calendar"]].map(x=><div className="alert" key={x[0]}><span className={x[2]}>●</span><div><b>{x[0]}</b><small>{x[1]}</small></div></div>)}</div>}
function Assistant(){return <div className="assistant"><div className="assistant-title"><Sparkles size={16}/><b>AI Assistant</b></div><p>Your portfolio has become overly concentrated in technology. Consider reducing exposure before adding another tech position.</p><div className="ask">Ask a question... <span>➤</span></div></div>}
function Watchlist({assets,onOpen}:{assets:Asset[],onOpen:(a:Asset)=>void}){return <div className="watchlist"><Header title="Watchlist" action="View all"/>{assets.slice(0,5).map(a=><button onClick={()=>onOpen(a)} key={a.symbol}><Logo symbol={a.symbol}/><span><b>{a.name}</b><small>{a.symbol}</small></span><em className={a.change_pct!=null&&a.change_pct<0?"down":"up"}>{a.price?money(a.price):"—"} <strong>{pct(a.change_pct)}</strong></em></button>)}</div>}
function PageContent({page,assets,onOpen}:{page:Page,assets:Asset[],onOpen:(a:Asset)=>void}){return <section className="page-panel"><Header title={page}/>{page==="Opportunity Scanner"?<div className="large-table">{assets.map(a=><button onClick={()=>onOpen(a)} key={a.symbol}><Logo symbol={a.symbol}/><span><b>{a.name}</b><small>{a.symbol} · {a.market}</small></span><strong>{a.score}/100</strong><em>{money(a.price,a.currency)}</em><i>{pct(a.change_pct)}</i></button>)}</div>:<><div className="empty-hero"><Target size={30}/><h2>{page}</h2><p>This module is connected to the platform architecture and preserves deterministic calculations separately from AI synthesis.</p><div><span>Live data</span><span>Audit trail</span><span>Human approval</span></div></div><div className="feature-grid"><div><Gauge/><b>Evidence-first analytics</b><p>Source, timestamp and data quality remain visible before a decision is generated.</p></div><div><ShieldAlert/><b>Execution controls</b><p>Live trading stays disabled by default and requires explicit human approval.</p></div><div><LineChart/><b>Reproducible calculations</b><p>Backtests, risk and portfolio calculations are deterministic and testable.</p></div></div></>}</section>}
function AssetModal({asset,close}:{asset:Asset,close:()=>void}){return <div className="modal" onClick={close}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}><X/></button><span className="eyebrow">ASSET INTELLIGENCE</span><h2>{asset.name} ({asset.symbol})</h2><div className="modal-price"><strong>{money(asset.price,asset.currency||"USD")}</strong><em className={asset.change_pct!=null&&asset.change_pct<0?"down":"up"}>{pct(asset.change_pct)}</em></div><div className="modal-grid"><div><b>AI score</b><strong>{asset.score}/100</strong></div><div><b>Sector</b><strong>{asset.sector}</strong></div><div><b>Provider</b><strong>{asset.provider}</strong></div><div><b>Status</b><strong>{asset.status}</strong></div></div><p className="notice">Investment evidence is only considered current when source data is available and timestamped. No live order is created from this view.</p></div></div>}
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
